name: Release
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Semver type of new version (major / minor / patch)"
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  # Run the linting and tests
  hadolint:
    uses: SkynetLabs/.github/.github/workflows/reusable_dockerfile_lint.yml@master

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - name: Install analyze
        run: go install gitlab.com/NebulousLabs/analyze@latest
      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.0
      - name: Update Dependecies and Clean Up
        run: make deps
      - name: Lint
        run: make lint
      - name: Run unit tests
        run: make test
      - name: Start Mongo Container
        run: make start-mongo
      - name: Run Long tests
        run: make test-long-ci
